---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/init

inputs:
- name: yagnats
  path: gopath/src/github.com/cloudfoundry/yagnats

run:
  path: gopath/src/github.com/cloudfoundry/yagnats/ci/tasks/test.sh
