---
jobs:
- name: test
  public: true
  plan:
    - get: yagnats
      trigger: true
    - get: daily
      trigger: true
    - task: test
      file: yagnats/ci/tasks/test.yml

resources:
- name: yagnats
  type: git
  source:
    uri: https://github.com/cloudfoundry/yagnats
    branch: master

- name: daily
  type: time
  source:
    interval: 24h
